export const alphabetical = (values: string[]) =>
  [...values].sort((a, b) => a.localeCompare(b, 'pt-BR', { sensitivity: 'base' }));
export const VEHICLE_BRANDS = alphabetical([
  'Abarth',
  'Agrale',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'BYD',
  'Caoa Chery',
  'Changan',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Dafra',
  'Dodge',
  'Ducati',
  'Ferrari',
  'Fiat',
  'Ford',
  'GWM',
  'Harley-Davidson',
  'Honda',
  'Hyundai',
  'Iveco',
  'JAC',
  'Jaguar',
  'Jeep',
  'Kawasaki',
  'Kia',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lifan',
  'Maserati',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Peugeot',
  'Porsche',
  'RAM',
  'Renault',
  'Royal Enfield',
  'Scania',
  'Shineray',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Triumph',
  'Volkswagen',
  'Volvo',
  'Yamaha',
]);
export const VEHICLE_COLORS = alphabetical([
  'Amarelo',
  'Azul',
  'Bege',
  'Branco',
  'Bronze',
  'Cinza',
  'Dourado',
  'Laranja',
  'Marrom',
  'Prata',
  'Preto',
  'Rosa',
  'Roxo',
  'Verde',
  'Vermelho',
]);
